### ISSUE TITLE
peerj_user.encrypt.id dependency

### ISSUE THREAD

**Issue by thomask** [PeerJ/sixpack-bundle#12]
In `PeerjSixpackOverideCompilerPass.php:24` I see this line:

`$definition->addArgument(new Reference('peerj_user.encrypt.id'));`

I am not sure what it does, but it looks like an internal dependency for your app. The looks to work find when commenting this line. Are you able to remove it?

Thanks!

**Comment by urg** [comment]
We're not quite ready for public release on this bundle yet.  #5 will remove that dependency, but in the meantime, its fine to remove that line in your fork.

**Comment by thomask** [comment]
Ok thanks. I'd love to help and work towards a public release (already created a pull request for #2). Do you have a certain timeframe in mind for a public release?

**Comment by urg** [comment]
I should be able to merge in your change and remove the dependency in the next day or 2.  I think most of the other issues are more additional features. 

The one thing I'm not too sure on is #3 - do you know (or have to research) best practice on handling migrations in a bundle?  Or is that a non-issue?

**Comment by thomask** [comment]
I am not sure. I know that the [StofDoctrineExtensionsBundle](https://github.com/stof/StofDoctrineExtensionsBundle) makes use of annotations. To me, it is a non issue anyway. If someone doesn't like it, they can always create a pull request right? :)

Furthermore (we're gonna get real off topic), would it be possible to use something like a listener (or anything else) for adding the cookie to the response? I almost never instantiate a Response in my controllers because I make a lot of use of the `@Template` annotation.

**Comment by urg** [comment]
I think you should be able to add a listener for the kernel response, which also has the peerj sixpack service(s) and in the onKernelResponse call setCookie in the service.  If you add to a PR, as long as its optional, would be happy to include.

**Comment by thomask** [comment]
Ok, I will see what I can do. It's just that the setPhpCookie option induces an error:

```
Cannot modify header information - headers already sent by...
```

I just don't want to use the `$sixpack_client->setCookie($response);` line. Any thoughts would be appreciated.

**Comment by thomask** [comment]
Just noticed, it only happens on with the user client. Must be something else then. I will see what I can find.

**Comment by urg** [comment]
The sixpack client doesn't work very well with symfony, which is why we made the setPhpCookie option and disabled by default.

Is there a specific issue with using the setCookie in a listener for the onKernelResponse?  That listener should have a response object, so should just be 1 line of code and a few lines in the services config.  If you set in the listener, then you shouldn't need to set the response in the controller.

**Comment by thomask** [comment]
The setPhpCookie option works perfectly fine for me. So I'll just use that.

I try to keep onKernelResponse listeners to a minimum&hellip;
