### ISSUE TITLE
BasicSixPackClient is instantiated at every request

### ISSUE THREAD

**Issue by thomask** [PeerJ/sixpack-bundle#15]
Hi, I noticed that the client is instantiated on every request, also on pages that are not included in test. Is this intended behaviour? Normally this wouldn't be a biggie, but it looks like a lot of stuff happens as a result from logic in the constructors (like setting cookies)

I have tried to define all services as lazy, but that's not working. Any clues?

**UPDATE**
Has something to do with the twig extension

**Comment by urg** [comment]
http://symfony.com/doc/current/cookbook/templating/twig_extension.html
"Keep in mind that Twig Extensions are not lazily loaded"

Could probably move the instantiation of the SixPackBase class from the construction to the getClient method to minimize impact.  Should also update to make the twig extension optional.

**Comment by thomask** [comment]
Injecting the container instead of the client in the twig extension is also an option, especially seeing that it should be possible to define the client from within twig.

By the way, same goes for the loginListener. Currently testing a solution. I'll let you know

**Comment by thomask** [comment]
Moving the SixPackBase instantiation to getClient method seems like the best solution. Otherwise you'll end up injecting the container all over the place.

I'll create a PR
